spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://board.cwpsrsz0hy7c.ap-northeast-2.rds.amazonaws.com/boarddb
    username: admin
    password: kms92460771*
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 1000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
#    open-in-view: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp



logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


